# Generated by Django 3.2.6 on 2022-03-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_image_date_uploaded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
