# Generated by Django 3.2.6 on 2022-04-21 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_videoresult_scape_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('audio_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('wav_file', models.FileField(null=True, upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav'])])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
