# Generated by Django 3.2.6 on 2022-01-20 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_image_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresult',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 21, 59, 6, 259115)),
        ),
    ]
