# Generated by Django 3.2.6 on 2022-04-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_audio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
