# Generated by Django 3.2.6 on 2022-02-04 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20220120_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification_agreement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pw_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tci_rs_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_survey_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 19, 16, 38, 784746)),
        ),
    ]
