# Generated by Django 3.2.6 on 2022-06-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='survey',
            field=models.JSONField(null=True),
        ),
    ]
