# Generated by Django 3.2.6 on 2022-02-25 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20220225_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoresult',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 19, 27, 11, 74970)),
        ),
    ]
