# Generated by Django 3.2.6 on 2022-03-18 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_auto_20220225_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Name', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 5, 12, 44, 324016)),
        ),
    ]
