# Generated by Django 3.2.6 on 2022-03-18 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_auto_20220318_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 5, 16, 9, 288194)),
        ),
    ]
