# Generated by Django 3.2.6 on 2022-03-18 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_alter_image_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 8, 25, 55, 696079)),
        ),
    ]
