# Generated by Django 3.2.6 on 2022-03-18 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0015_alter_image_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresult',
            name='survey',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 9, 59, 11, 239885)),
        ),
    ]
